### ISSUE TITLE
Release Expat 2.2.7

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#254]
Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build and test Windows installer (Karl)
- [x] SourceForge:
  - [x] Upload Windows installer
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new installer binary default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-309232686) and push it
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer (Karl)
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the xml-dev mailing list ([mail](http://lists.xml.org/archives/xml-dev/201906/msg00019.html))
  - [x] Blog about it at `blog.hartwork.org`: [post](https://blog.hartwork.org/posts/expat-227-with-security-fixes-has-been-released/)
    - [x] Submit to Hacker News ([thread](https://news.ycombinator.com/item?id=20285491))
  - [x] Blog about it at `xml.com`: [post](https://www.xml.com/news/2019-06-expat-227/)
- [x] (Bump ebuild in Gentoo)

Specific to 2.2.7:
- [x] Request CVE for #186 / #262 — submitted 2019-06-20, received [CVE-2018-20843](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20843) on 2019-06-24
  - [x] Add CVE to change log
  - [x] (Open security bug in Gentoo — https://bugs.gentoo.org/688734)

**Comment by Mistuke** [comment]
Hi,

I was wondering why the release tarballs still require `autoreconf`. As in why isn't just a `configure` file distributed?

The reason I ask is because libexpath requires a specific version of autoreconf which of course differs from the version from other projects.

I understand why the git repo doesn't contain one, just wondering why the tarballs don't.

**Comment by hartwork** [comment]
> I was wondering why the release tarballs still require `autoreconf`. As in why isn't just a `configure` file distributed?

Hi! I have good and bad news: You have the wrong file, the [release archive](https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2) does contain `configure`.

> The reason I ask is because libexpath requires a specific version of autoreconf which of course differs from the version from other projects and we're building `libexpat` as part of a much wider toolchain. This then ends up with a version mismatch and requires build scripts to change the path of tools..

May I ask what version of Automake, Autoconf, libtool you have that are not good enough to `autoreconf` expat? What distro are you basing on?

**Comment by Mistuke** [comment]
> Hi! I have good and bad news: You have the wrong file, the release archive does contain configure.

Ah indeed! I was using the source tarballs but of course that's just the snapshot of the repo!

> May I ask what version of Automake, Autoconf, libtool you have that are not good enough to autoreconf expat? What distro are you basing on?

We have some projects that unfortunately require exactly `2.64` so this is too old for libexpat.

We're building Automaker etc them from source so not tied to a particular distro but most of the builds happen on Ubuntu 16.04 or 18.04 and RHEL5

**Comment by hartwork** [comment]
2.2.7 is coming up in the next few days. If anyone wants to give latest Git `master` a spin in their environment, now would be a good time :smile:
