### ISSUE TITLE
Release Expat 2.2.8

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#342]
Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer
- [x] SourceForge:
  - [x] Upload Windows installer
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new installer binary default download for Windows
- [x] GitHub: 
  - [x] Create new release
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-309232686) and push it — https://github.com/libexpat/libexpat/releases/tag/R_2_2_8
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the xml-dev mailing list — http://lists.xml.org/archives/xml-dev/201909/msg00013.html
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-228-with-security-fixes-has-been-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=20972658
  - [x] Blog about it at `xml.com` — https://www.xml.com/news/2019-09-expat-228/
- [x] (Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/47054881ebeb16ed19bd7f5f0a58d64339377951)

Specific to 2.2.8:
- [x] Handle security issue #317 / #318
  - [x] Request CVE  — https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15903
  - [x] Add CVE to change log
  - [x] Open security bug in Gentoo — https://bugs.gentoo.org/694362
  - [x] Mail security teams
