### ISSUE TITLE
Release Expat 2.2.9

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#351]
Note: This release is done only to get the re-rename from `expat.dll` to `libexpat.dll` out the door. Most of the normal release steps (a la #342 for 2.2.8) won't be done for 2.2.9: No announcements etc. Users should get `libexpat.dll` both from Git and from the latest release binary, that's all.

- [x] Bump `.so` version info, document in change log
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer
- [x] SourceForge:
  - [x] Upload Windows installer
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new installer binary default download for Windows
- [x] GitHub: 
  - [x] Create new release
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-309232686) and push it — https://github.com/libexpat/libexpat/releases/tag/R_2_2_9
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer
