### ISSUE TITLE
Release Expat 2.2.10

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#415]
Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI
- [x] SourceForge:
  - [x] Upload Windows installer
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new installer binary default download for Windows
- [x] GitHub: 
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_2_10
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-309232686) and push it
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the xml-dev mailing list — http://lists.xml.org/archives/xml-dev/202010/msg00000.html
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-2-2-10-has-been-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=24674810
  - [x] Blog about it at `xml.com` — https://www.xml.com/news/2020-10-expat-2210/
- [x] (Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/fc368b5efce6e04326900da50a01bc17eae98071)

Specific to 2.2.10:
n/a
