### ISSUE TITLE
Get bundled copies of pre-2.2.1 Expat updated / removed

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#44]
This ticket is a great example of [why not to bundle dependencies](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies)...

There are [>11.000 copies of Expat on GitHub alone](https://github.com/search?utf8=%E2%9C%93&q=filename%3Aexpat.h+XML_MAJOR_VERSION&type=). While that's too many to care about, high-profile users of Expat (on GitHub or not) that come with their own copy should not remain without an update for too long. Among them:
* [x] [Alpine Linux](https://git.alpinelinux.org/cgit/aports/tree/main/expat)
* [x] [ALT Linux](https://packages.altlinux.org/en/Sisyphus/srpms/expat) — mail sent
* [ ] [Amazon Kindle](https://www.amazon.in/gp/help/customer/display.html?nodeId=200499360) — mail sent to security team
* [ ] Android (https://github.com/android/platform_external_expat) — mail to Android security sent, again on 2017-08-20, again on 2017-11-15
* [x] [Apache OpenOffice](https://github.com/apache/openoffice/blob/HEAD/main/expat/makefile.mk#L41) — mail sent to security team, [bug](https://bz.apache.org/ooo/show_bug.cgi?id=127461) opened
* [ ] [Apple](https://opensource.apple.com/tarballs/expat/) — mail sent to security team
* [x] Arch Linux — mail sent
* [x] [bah.mod](https://github.com/maxmods/bah.mod/blob/master/expat.mod/expat/lib/xmlparse.c)
* [x] [BenzoRoms](https://github.com/BenzoRoms/external_expat)
* [x] [Buildroot](https://git.busybox.net/buildroot/tree/package/expat/expat.mk)
* [ ] [Audacity](https://github.com/audacity/audacity/tree/master/lib-src/expat/lib) — mail sent
* [x] [Chromium](https://chromium.googlesource.com/chromium/src/+/master/third_party/expat/files/lib/) — mail to security team sent, there is a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=735752) now
* [ ] [Cisco FXOS](http://cisco-images.test.edgekey.net/c/dam/en/us/td/docs/security/firepower/fxos/fxos221/license/open-source/Cisco_FXOS_2_2_1.pdf) — mail sent
* [x] [ClamAV (for Windows?)](https://github.com/vrtadmin/clamav-devel/tree/master/win32/clamav-for-windows/sigui/wxWidgets-2.9.1/src/expat/lib) — [bug](https://bugzilla.clamav.net/show_bug.cgi?id=11858) opened
* [x] CMake — [bug](https://gitlab.kitware.com/cmake/cmake/issues/16997) opened
* [ ] [coapp/NuGet](https://www.nuget.org/packages/expat/) — [bug](https://github.com/coapp-packages/expat/issues/2) opened
* [ ] [Coin3D](https://bugs.gentoo.org/show_bug.cgi?id=297644) — [bug](https://bitbucket.org/Coin3D/coin/issues/135/) opened
* [x] [crDroid](https://github.com/crdroidandroid/android_external_expat) — [updated](https://github.com/crdroidandroid/android_external_expat/commit/2302f151511455b705e6ce4ce610a894cb4428e0)
* [x] [Cygwin](https://cygwin.com/packages/x86_64/expat/) — mail sent
* [x] Debian — mail sent
* [x] DragonFlyBSD — [bug](https://github.com/DragonFlyBSD/DPorts/issues/190) opened
* [x] [Exherbo](http://git.exherbo.org/arbor.git/tree/packages/dev-libs/expat) — mail sent
* [x] [Far-NetBox](https://github.com/michaellukashov/Far-NetBox/tree/master/libs/expat)
* [ ] FBReader for Android — [bug](https://github.com/geometer/FBReaderJ/issues/456) opened
* [x] Fedora — mail sent, same contact as Red Hat
* [x] [Fink](http://pdb.finkproject.org/pdb/package.php/expat1) — mail sent
* [x] fre:ac CDK / [BoCA](https://github.com/enzo1982/BoCA/tree/master/components/playlist/xspf/expat) — mail sent
* [x] [FreeBSD](https://svnweb.freebsd.org/ports/head/textproc/expat2/) — mail sent
* [x] Gentoo — [package bumped](https://github.com/gentoo/gentoo/commit/2466807370676c8702e2512e1742cbf6a1aa1bd4), [bug](https://bugs.gentoo.org/show_bug.cgi?id=622046) created
* [x] Gobo Linux — mail sent, [bug](https://github.com/gobolinux/Recipes/issues/20) opened by now as well
* [x] [GuixSD](https://www.gnu.org/software/guix/packages/e.html) — mail sent
* [x] Harbour — [bug](https://github.com/harbour/core/issues/157) opened
* [x] Harbour fork — upstream [updated by itself](https://github.com/vszakats/harbour-core/commit/cc5efa5f361faf1fd75bd5df07f4895566ad9a30)
* [x] HaikuPorts — [bug](https://github.com/haikuports/haikuports/issues/1453) opened
* [x] hexpat — existing [bug](https://github.com/the-real-blackh/hexpat/issues/2) bumped and fixed, [bundle bypass bug](https://github.com/the-real-blackh/hexpat/issues/8) opened as well
* [x] [homebrew](http://brewformulas.org/Expat)
* [x] KomodoEdit — [bug](https://github.com/Komodo/KomodoEdit/issues/2659) opened
* [x] [LibreOffice](https://cgit.freedesktop.org/libreoffice/core/tree/download.lst) — mail sent to security team
* [x] libwww — [bug](https://github.com/w3c/libwww/issues/6) and [pull request](https://github.com/w3c/libwww/pull/7) opened; [bundle removed](https://github.com/w3c/libwww/pull/9) eventually
* [x] [Linuxbrew](http://braumeister.org/formula/expat)
* [x] [Linux from Scratch](http://www.linuxfromscratch.org/lfs/view/development/chapter06/expat.html)
* [ ] LuaPlus — [bug](https://github.com/jjensen/luaplus51-all/issues/17) opened
* [ ] [luapower-expat](https://github.com/luapower/expat/tree/master/csrc/expat/src) — [bug](https://github.com/luapower/expat/issues/5) opened
* [x] [macchina.io](https://github.com/macchina-io/macchina.io/blob/develop/platform/XML/src/xmlparse.cpp)
* [x] [MacPorts](https://github.com/macports/macports-ports/tree/master/textproc/expat) — mail sent
* [x] [Mageia](https://mageia.pkgs.org/cauldron/mageia-core-release-i586/libexpat-devel-2.2.1-1.mga6.i586.rpm.html) — mail sent
* [ ] [Mediola AIO Gateway V5 Plus](http://www.mediola.com/contrib-v5-plus-os) — mail sent
* [x] MeshBSD — [bug](https://github.com/hmatyschok/MeshBSD/issues/6) opened
* [x] meta-debian — [bug](https://github.com/meta-debian/meta-debian/issues/68) opened
* [ ] MINIX — [bug](https://github.com/Stichting-MINIX-Research-Foundation/minix/issues/228) opened
* [ ] Mono
  * [Bundled at mono/linux-packaging-skiasharp](https://github.com/mono/linux-packaging-skiasharp/tree/HEAD/externals/skia/third_party/externals/expat/lib) — [bug](https://github.com/mono/linux-packaging-skiasharp/issues/1) opened
  * https://github.com/mono/linux-packaging-mono/blob/HEAD/external/bockbuild/packages/expat.py — [bug](https://github.com/mono/linux-packaging-mono/issues/3) opened
  * https://github.com/mono/bockbuild/blob/master/packages/expat.py — [bug](https://github.com/mono/linux-packaging-mono/issues/3) opened
* [ ] Mozilla Firefox/Gecko — mail to security team sent
  * Mercurial: https://hg.mozilla.org/mozilla-central/file/tip/parser/expat/lib/
  * Git: https://github.com/mozilla/gecko-dev/tree/HEAD/parser/expat/lib
* [ ] Mozilla Servo (see https://github.com/servo/libexpat/tree/master/expat/lib) — mail to security team sent
* [x] [my-devices.net SDK](https://github.com/my-devices/sdk/blob/master/XML/src/xmlparse.cpp)
* [x] [NetBSD](http://pkgsrc.se/textproc/expat) — mail sent
* [x] NixOS — mail sent
* [x] [node-expat](https://github.com/astro/node-expat/tree/master/deps/libexpat) — [bug](https://github.com/astro/node-expat/issues/175) opened, [pull request](https://github.com/astro/node-expat/pull/176) opened by now
* [x] [NXLog](https://nxlog.co/products/nxlog-community-edition/download) binaries — mail sent
* [ ] OpenCOLLADA — [bug](https://github.com/KhronosGroup/OpenCOLLADA/issues/535) opened
* [x] [OpenBSD](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libexpat/) — mail sent
* [x] [OpenCSW](https://www.opencsw.org/package/expat/) — mail sent
* [x] [openSUSE](https://build.opensuse.org/package/show/devel:libraries:c_c++/expat) — mail sent
* [ ] Oracle [1](https://docs.oracle.com/cd/E52095_01/html/E28370/goqbm.html) [2](http://docs.oracle.com/cd/E80920_01/DBMLI/exadata-third-party-licenses.htm#DBMLI109) — mail to security team sent
* [x] [Parabola](https://www.parabola.nu/packages/testing/x86_64/expat/)
* [x] [PLD Linux](https://git.pld-linux.org/?p=packages/expat.git;a=summary) — mail sent
* [x] POCO — [bug](https://github.com/pocoproject/poco/issues/1760) found, fixed by now
* [x] Poedit — [bug](https://github.com/vslavik/poedit/issues/407) opened
* [ ] PureMail — [bug](https://github.com/hemaprathaban/PureMail/issues/1) opened
* [x] Python — mail sent, upstream now has a [bug for it](https://bugs.python.org/issue30694)
* [x] Red Hat — mail sent
* [ ] [SMA COM GATEWAY](http://files.sma.de/dl/29238/COMGW-10-OpenSource-TI-en-10.pdf) — mail sent
* [ ] [Sophos Anti-Virus](http://downloads.sophos.com/readmes/savl_9_P_rneng.html) — mail sent
* [x] [Solus Project](https://dev.solus-project.com/source/expat/)
* [ ] [Speed Dreams](https://bugs.gentoo.org/show_bug.cgi?id=315951) — [bug](https://sourceforge.net/p/speed-dreams/tickets/970/) opened
* [x] Swift XMPP — [bug](https://github.com/swift/swift/issues/70) opened
* [x] [T2 project](https://svn.exactcode.de/t2/trunk/package/base/expat/expat.desc) — mail sent
* [x] ~~[TORCS](https://bugs.gentoo.org/show_bug.cgi?id=253517) — [mail](https://sourceforge.net/p/torcs/mailman/message/35906268/) sent; [Expat fork txml not considered Expat upstream](https://sourceforge.net/p/torcs/mailman/message/35906280/)~~
* [x] [TortoiseSVN](https://svn.code.sf.net/p/tortoisesvn/code/trunk/ext/expat/lib/xmlparse.c)
* [x] Ubuntu — mail sent
* [x] [Void Linux](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/expat/template)
* [ ] vstgui — [bug](https://github.com/steinbergmedia/vstgui/issues/22) opened and fixed but unfixed by part of [this bug](https://github.com/steinbergmedia/vstgui/issues/29)
* [x] VTK — [bug](https://gitlab.kitware.com/vtk/vtk/issues/17070) opened
* [x] [Webkit / libwebrtc](https://github.com/WebKit/webkit/blob/master/Source/ThirdParty/libwebrtc/Source/third_party/expat/files/lib/expat.h) — mail sent to security team, unused bundle removed by now
* [ ] [WinMerge 2](https://sourceforge.net/p/winmerge/code/HEAD/tree/trunk/Externals/expat/lib/) — end of life?
* [x] WinSCP — mail sent
* [x] wxWidgets — [pull request](https://github.com/wxWidgets/wxWidgets/pull/503) created, then [another one](https://github.com/wxWidgets/wxWidgets/pull/524)
* [x] [Yocto Project](https://git.yoctoproject.org/cgit.cgi/poky/tree/meta/recipes-core/expat) — mail sent
* [x] [(Index Data) Zebra](http://www.indexdata.com/zebra) — mail sent
* [x] [zeroc-ice/NuGet](https://github.com/zeroc-ice/expat) — mail sent, new repo [zeroc-ice/*lib*expat](https://github.com/zeroc-ice/libexpat) created, [NuGet](https://www.nuget.org/packages?q=expat) 4 of 4 updated
&lt;to be found&gt;

So the task is to
* identify relevant users with a bundled or packaged copy of pre-2.2.1 Expat
* Initiate / help their process to update

If either sounds like fun to you, please get in touch.

Best, Sebastian

Current template I use:
> SUBJECT: Bundles vulnerable copy of Expat - please update to 2.2.1
>
> Hi!
> 
> This repository bundles an outdated vulnerable copy of Expat VERSIONVERSION. Please update your copy to version 2.2.1 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes. If you happen to run into compile errors, please check the post-2.2.1 commits in Git as well. Thank you! 
>
>Best
>
>&amp;nbsp;
>NAMENAME

**Comment by scottmc** [comment]
Haiku updated with https://github.com/haikuports/haikuports/commit/2ee42a5529a33e0b5e68047dca1eb11727bd5285
