### ISSUE TITLE
Release Expat 2.3.0

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#445]
Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere
- [x] Fill release date
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/project/libexpat/libexpat/builds/38391105/artifacts
- [x] SourceForge:
  - [x] Upload Windows installer
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new installer binary default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-309232686) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_3_0
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list — http://lists.xml.org/archives/xml-dev/202103/msg00014.html
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-2-3-0-has-been-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=26582035
  - [x] Blog about it at `xml.com` — https://www.xml.com/news/2021-03-expat-230/
- [x] (Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/f62d092eb352ee2d5926d9c6fb6ff461c679ab95)
- [x] (~Ask CMake to update their bundled copy (in case of relevant bugfixes)~)

Specific to 2.3.0:
n/a
