### ISSUE TITLE
Release Expat 2.4.0

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#479]
Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/project/libexpat/libexpat/builds/39279558/artifacts
- [x] Build Windows binaries zip file from installer a la https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-309232686) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_4_0
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer and binaries zip file
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list — http://lists.xml.org/archives/xml-dev/202105/msg00011.html
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/cve-2013-0340-billion-laughs-fixed-in-expat-2-4-0/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=27257272
  - [x] Blog about it at `xml.com` — https://www.xml.com/news/2021-05-expat-240-and-241/
- [x] (Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/da6c3ff9651e40ded9cb5e6ea16ae8e247232b68)
- [x] (Ask CMake to update their bundled copy (in case of relevant bugfixes) — https://gitlab.kitware.com/cmake/cmake/-/issues/22231)

Specific to 2.4.0:
- [x] Additional communication due to security aspects, e.g.
  - [x] anaconda — mailed on 2021-05-24
  - [x] Apple product security  — mailed on 2021-05-24
  - [x] Conan — https://github.com/conan-io/conan-center-index/issues/5610
  - [x] Gentoo — https://bugs.gentoo.org/791703
  - [x] hexpat — https://github.com/the-real-blackh/hexpat/issues/11
  - [x] nixos — https://github.com/NixOS/nixpkgs/pull/124212
  - [x] rexpat — https://github.com/immunant/rexpat/issues/62
  - [x] xmp-toolkit-rs — https://github.com/adobe/xmp-toolkit-rs/issues/18
