### ISSUE TITLE
Release Expat 2.4.2

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#525]
Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/api/buildjobs/xvxceoqs2fd73s4a/artifacts/expat%2Fwin32%2Fexpat-win32bin-2.4.2.exe
- [x] Build Windows binaries zip file from installer a la https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-309232686) and push it
  - [x] Create new release — [TODO_LINK](https://github.com/libexpat/libexpat/releases/tag/R_2_4_2)
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/
  - [x] ~Mail Expat distro maintainers directly~
  - [x] ~Write to the `xml-dev` mailing list — TODO_LINK~
  - [x] ~Blog about it at `blog.hartwork.org` — TODO_LINK~
    - [x] ~Submit to Hacker News — TODO_LINK~
  - [x] ~Blog about it at `xml.com` — TODO_LINK~
- [x] (Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/829abbc881ba337ca9f1333d9943e893ab850720
- [x] ~(Ask CMake to update their bundled copy (in case of relevant bugfixes) — TODO_LINK)~

Specific to 2.4.2:
n/a
