### ISSUE TITLE
Release Expat 2.4.3

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#533]
Issues to be fixed prior to the release:
- #531
- #532

Pull requests to be merged prior to the release:
- #534
- #538
- #539
- #541
- #543

Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/project/libexpat/libexpat/builds/42220232/artifacts
- [x] Build Windows binaries zip file from installer a la https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + `.asc` GPG signature (#193)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_4_3
  - [x] Upload source tarball + `.asc` GPG signature (#193)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list — http://lists.xml.org/archives/xml-dev/202201/msg00145.html
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-2-4-3-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=29957018
  - [x] Blog about it at `xml.com` — https://www.xml.com/news/2022-01-expat-243-released/
  - [x] Ask CMake to update their bundled copy (in case of relevant bugfixes) — https://gitlab.kitware.com/cmake/cmake/-/issues/23113
  - [x] Ask CPython to update their bundled copy (in case of relevant bugfixes) — https://bugs.python.org/issue46400
- [x] Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/f37a82a6ab4bee144e8a0824a77c8bb8176437db

Specific to 2.4.3:
- security aspects

Related downstreams issues and pull requests:
- AOSC — https://github.com/AOSC-Dev/aosc-os-abbs/issues/3753
- Conan — https://github.com/conan-io/conan-center-index/issues/8940
- Gobo Linux — https://github.com/gobolinux/Recipes/issues/150
- msys2 — https://github.com/msys2/MINGW-packages/issues/10559
- NixOS — https://github.com/NixOS/nixpkgs/pull/155253
- Pisi Linux — https://github.com/pisilinux/core/issues/1311
- Spack — https://github.com/spack/spack/pull/28435
- vcpkg — https://github.com/microsoft/vcpkg/issues/22551
