### ISSUE TITLE
Release Expat 2.4.4

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#552]
Issues to be fixed prior to the release:
- n/a

Pull requests to be merged prior to the release:
- n/a

Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — [TODO](https://ci.appveyor.com/project/libexpat/libexpat/builds/42383768/artifacts)
- [x] Build [Windows binaries zip file](https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183) from installer
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + [`.asc` GPG signature](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_4_4
  - [x] Upload source tarball + [`.asc` GPG signature](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Let the community know:
  - [x] News item on https://libexpat.github.io/ project website — https://github.com/libexpat/libexpat.github.io/commit/8460163bb39299a29e81a8af7397e1664a26e924
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list — http://lists.xml.org/archives/xml-dev/202201/msg00253.html
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-2-4-4-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=30153393
  - [x] Blog about it at `xml.com` — TODO_LINK
- [x] Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/7fd316fb024f9d26a1931314740c3ac4ca29f806

Specific to 2.4.4:
- security aspects

Related downstreams issues and pull requests:
- Bundled copies
  - CMake — https://gitlab.kitware.com/cmake/cmake/-/issues/23165
  - CPython — https://bugs.python.org/issue46400
  - node-expat — https://github.com/astro/node-expat/issues/215
- Packaging
  - AOSC — https://github.com/AOSC-Dev/aosc-os-abbs/issues/3753
  - Conan — https://github.com/conan-io/conan-center-index/pull/9111
  - Gentoo — https://github.com/gentoo/gentoo/commit/7fd316fb024f9d26a1931314740c3ac4ca29f806
  - Gobo Linux — https://github.com/gobolinux/Recipes/issues/151
  - msys2
    - https://github.com/msys2/MINGW-packages/pull/10627
    - https://github.com/msys2/MSYS2-packages/pull/2831
  - NixOS
    - https://github.com/NixOS/nixpkgs/pull/156607
    - https://github.com/NixOS/nixpkgs/pull/157052
    - https://github.com/NixOS/nixpkgs/pull/157586
  - Pisi Linux — https://github.com/pisilinux/core/issues/1311
  - Spack — https://github.com/spack/spack/pull/28692
  - vcpkg — https://github.com/microsoft/vcpkg/issues/22551
