### ISSUE TITLE
Release Expat 2.4.5

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#557]
Issues to be fixed prior to the release:
- multiple security issues, see PRs below

Pull requests to be merged prior to the release:
- #558
- #559
- #560 
- #561
- #562

Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/project/libexpat/libexpat/builds/42632568/artifacts
- [x] Build [Windows binaries zip file](https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183) from installer
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_4_5
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Website
  - [x] Add news item — https://github.com/libexpat/libexpat.github.io/commit/40372e78b7b27d151348380d5ea1e899af5f0dc1
  - [x] Sync API documentation — https://github.com/libexpat/libexpat.github.io/commit/f3d748695be8ede1109b12dcfdf6109d9395b7fa
- [x] Let the community know:
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list — TODO
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-2-4-5-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=30393614
  - [x] Blog about it at `xml.com` — TODO
- [x] Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/05a3f5ee4da9487f6019e3578701cbd6ee775e78

Specific to 2.4.5:
- security aspects

Related downstreams issues and pull requests:
- Bundled copies
  - Android — mail sent 2022-02-19
  - Apache OpenOffice — mail sent 2022-02-19
  - Chromium — mail sent 2022-02-19
  - CMake — https://gitlab.kitware.com/cmake/cmake/-/issues/23250
  - CPython — https://bugs.python.org/issue46794
  - LibreOffice — mail sent 2022-02-19
  - node-expat — https://github.com/astro/node-expat/issues/215
- Packaging
  - AOSC — https://github.com/AOSC-Dev/aosc-os-abbs/issues/3753
  - Conan — https://github.com/conan-io/conan-center-index/pull/9427
  - HaikuPorts — https://github.com/haikuports/haikuports/issues/6640
  - Gentoo — https://github.com/gentoo/gentoo/commit/05a3f5ee4da9487f6019e3578701cbd6ee775e78
  - Gobo Linux — https://github.com/gobolinux/Recipes/issues/152
  - msys2
    - https://github.com/msys2/MINGW-packages/pull/10801
    - https://github.com/msys2/MSYS2-packages/pull/2866
  - NixOS — https://github.com/NixOS/nixpkgs/pull/160826
  - Pisi Linux — https://github.com/pisilinux/core/issues/1311
  - Spack — https://github.com/spack/spack/pull/29086
  - vcpkg — mail sent 2022-02-19
