### ISSUE TITLE
Release Expat 2.4.6

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#567]
Regular releases:
- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/project/libexpat/libexpat/builds/42644750/artifacts
- [x] Build [Windows binaries zip file](https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183) from installer
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_4_6
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Website
  - [x] Add news item — https://github.com/libexpat/libexpat.github.io/commit/b38d31176dd69fd03536ac59d104640554b90bcb
  - [x] Sync API documentation — https://github.com/libexpat/libexpat.github.io/commit/d4e48ea15d8b9e475fe60de2374519037f45d687
- [x] Let the community know:
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list — http://lists.xml.org/archives/xml-dev/202202/msg00099.html
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-2-4-6-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=30408400
  - [x] Blog about it at `xml.com` — TODO
- [x] Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/d81dcbd9bb7da73dc8bd98d6ce7f6ab5d0aebd83

Related downstreams issues and pull requests:
- Packaging
  - Haiku — https://github.com/haikuports/haikuports/issues/6645
  - NixOS — https://github.com/NixOS/nixpkgs/pull/161090
  - Spack — https://github.com/spack/spack/pull/29100
