### ISSUE TITLE
Release Expat 2.4.7

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#578]
Release blockers:

- #572
- #577
- #581

Regular releases:

- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/project/libexpat/libexpat/builds/42793760/artifacts
- [x] Build [Windows binaries zip file](https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183) from installer
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_4_7
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Website
  - [x] Add news item — https://github.com/libexpat/libexpat.github.io/commit/5de5bc1749464adacb82ad39ec6df83e0352a840
  - [x] Sync API documentation — https://github.com/libexpat/libexpat.github.io/commit/84a18422823f2da2c32ff44f2e788ee69a43bd1b
- [x] Let the community know:
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list — TODO
  - [x] Blog about it at `blog.hartwork.org` — https://blog.hartwork.org/posts/expat-2-4-7-released/
    - [x] Submit to Hacker News — https://news.ycombinator.com/item?id=30561656
  - [x] Blog about it at `xml.com` — TODO
- [x] Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/eeaadcaacc1373623468129659ccd05b491379f1
