### ISSUE TITLE
Release Expat 2.4.8

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#590]
Regular releases:

- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI – https://ci.appveyor.com/project/libexpat/libexpat/builds/43044132/artifacts
- [x] Build [Windows binaries zip file](https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183) from installer
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release – https://github.com/libexpat/libexpat/releases/tag/R_2_4_8
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Website
  - [x] Add news item – https://github.com/libexpat/libexpat.github.io/commit/b4781614f33b23413990e809a8f94fc01b8d34e7
  - [x] Sync API documentation – https://github.com/libexpat/libexpat.github.io/commit/5fdc9622016ebc1bd8c7962d4520959acee7256a
- [ ] Let the community know:
  - [ ] Mail Expat distro maintainers directly
  - [ ] Write to the `xml-dev` mailing list – TODO
  - [ ] Blog about it at `blog.hartwork.org` – TODO
    - [ ] Submit to Hacker News – TODO
  - [ ] Blog about it at `xml.com` – TODO
- [x] Bump ebuild in Gentoo – https://github.com/gentoo/gentoo/commit/3216e358c8ca6205505e4f3ecba4b4f148a6d52d
