### ISSUE TITLE
Release Expat 2.4.9

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#642]
Regular releases:

- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI – https://ci.appveyor.com/project/libexpat/libexpat/builds/44818755/artifacts
- [x] Build [Windows binaries zip file](https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183) from installer
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release – https://github.com/libexpat/libexpat/releases/tag/R_2_4_9
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Website
  - [x] Add news item – https://github.com/libexpat/libexpat.github.io/commit/075b87193126d62cd8788f2d381d9be0ef00c3a1
  - [x] Sync API documentation – https://github.com/libexpat/libexpat.github.io/commit/468f7abcc8277aa2f3c72a553b1008bedf1c003d
- [x] Let the community know:
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the `xml-dev` mailing list – TODO
  - [x] Blog about it at `blog.hartwork.org` – https://blog.hartwork.org/posts/expat-2-4-9-released/
    - [x] Submit to Hacker News – https://news.ycombinator.com/item?id=32914513
  - [x] Blog about it at `xml.com` – TODO
- [x] Bump ebuild in Gentoo – https://github.com/gentoo/gentoo/commit/aacaf722fc8bc0f7cc113a5fe01fea450f044258

Specific to 2.4.9:
- security aspects

Related downstream issues and pull requests:
- Bundled copies 
  - poco — https://github.com/pocoproject/poco/issues/3805
- Packaging
