### ISSUE TITLE
Release Expat 2.5.0

### ISSUE THREAD

**Issue by hartwork** [libexpat/libexpat#667]
Regular releases:

- [x] Bump `.so` version info, document in change log
- [x] Bump release version everywhere (including `doc/reference.html`)
- [x] Fill release date (both change log and man page date)
- [x] `make distcheck` source tarballs using `./distribute.sh`
- [x] Build Windows installer using AppVeyor CI — https://ci.appveyor.com/project/libexpat/libexpat/builds/45175340/artifacts
- [x] Build [Windows binaries zip file](https://github.com/libexpat/libexpat/issues/461#issuecomment-819113183) from installer
- [x] SourceForge:
  - [x] Upload Windows installer and binaries zip file
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Make one new source tarball default download for all *but* Windows
  - [x] Make new binary zip file default download for Windows
- [x] GitHub: 
  - [x] [Create signed Git tag](https://github.com/libexpat/libexpat/issues/42#issuecomment-531406262) and push it
  - [x] Create new release — https://github.com/libexpat/libexpat/releases/tag/R_2_5_0
  - [x] Upload source tarballs + [`.asc` GPG signature files](https://github.com/libexpat/libexpat/issues/193#issuecomment-413191985)
  - [x] Upload Windows installer and binaries zip file
  - [x] Close current milestone and create a follow-up one
- [x] Website
  - [x] Add news item — https://github.com/libexpat/libexpat.github.io/commit/ce0e11d4ab1358d5a36b7facd71bc0388d6a9c5f
  - [x] Sync API documentation — https://github.com/libexpat/libexpat.github.io/commit/4f07d85428a3ad4a0067fc26aa21b0e22cb9d2a2
- [x] Let the community know:
  - [x] Mail Expat distro maintainers directly
  - [x] Write to the [`xml-dev` mailing list](https://www.xml.org/xml-dev/) — TODO
  - [x] Blog about it at [`blog.hartwork.org`](https://blog.hartwork.org/) — https://blog.hartwork.org/posts/expat-2-5-0-released/
    - [x] Submit to [Hacker News](https://news.ycombinator.com/) — https://news.ycombinator.com/item?id=33335230
  - [x] Blog about it at [`xml.com`](https://www.xml.com/) — https://www.xml.com/news/2022-10-expat-250/
- [x] Bump ebuild in Gentoo — https://github.com/gentoo/gentoo/commit/ac6bd67e437c096edbb3a656ae9566e9658bdcf0

Specific to 2.5.0:
- Security aspects

Related downstream issues and pull requests:
- Bundled copies 
  - …
- Packaging 
  - Gentoo — https://github.com/gentoo/gentoo/commit/ac6bd67e437c096edbb3a656ae9566e9658bdcf0
